# Generated by Django 4.0.4 on 2022-05-15 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Establecimientos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=40)),
                ('departamento', models.CharField(max_length=40)),
                ('rango_precios', models.CharField(max_length=50)),
                ('parqueadero', models.BooleanField()),
                ('correo', models.EmailField(max_length=254)),
                ('tarjeta_credito', models.BooleanField()),
                ('tarjetas_debito', models.BooleanField()),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('Restaurante', 'Restaurante'), ('Cafeteria', 'Cafeteria'), ('Bar', 'Bar'), ('CafeBar', 'CafeBar')], default='Restaurante', max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='establecimientos/banner')),
                ('imagen_banner', models.ImageField(upload_to='establecimientos/imagen')),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('nombreUsuario', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('password1', models.CharField(max_length=250)),
                ('password2', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.IntegerField()),
                ('comensales', models.IntegerField(max_length=100)),
                ('creado', models.DateField(auto_now_add=True)),
                ('editado', models.DateField(auto_now=True)),
                ('fecha_reserva', models.DateField()),
                ('hora_reserva', models.TimeField()),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.establecimientos')),
            ],
        ),
    ]
